services:
  - type: web
    name: nocodb
    env: docker
    repo: https://github.com/Et-Nyx/nocodb_deploy.git
    plan: free
    healthCheckPath: /
    disk:
      name: nocodb-data
      mountPath: /usr/app/data